name: TENx.io
favicon: null
layout_spectrum: 0.9211122221313417
typography_spectrum: 0.7482846383936703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#363636'
    - '#6ba51e'
    - '#cccccc'
    - '#28aafa'
    - '#000000'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
